/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basiccrud;

import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author 2ndyrGroupA
 */
public class Update extends javax.swing.JFrame {

    /**
     * Creates new form Update
     */
    public Update() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        gender = new javax.swing.JTextField();
        Id = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        uptdCancel1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Update Information");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(93, 23, 223, 41);

        updateBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateBtn);
        updateBtn.setBounds(200, 390, 103, 38);

        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        getContentPane().add(gender);
        gender.setBounds(130, 290, 150, 30);
        getContentPane().add(Id);
        Id.setBounds(130, 80, 60, 30);

        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });
        getContentPane().add(lastname);
        lastname.setBounds(130, 160, 150, 30);
        getContentPane().add(firstname);
        firstname.setBounds(130, 120, 150, 30);
        getContentPane().add(age);
        age.setBounds(130, 200, 150, 30);
        getContentPane().add(address);
        address.setBounds(130, 240, 150, 30);

        jLabel2.setText("Gender");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 280, 50, 40);

        jLabel3.setText("ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 80, 50, 40);

        jLabel4.setText("Firstname");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 110, 70, 40);

        jLabel5.setText("Lastname");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 150, 70, 40);

        jLabel6.setText("age");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 190, 50, 40);

        jLabel7.setText("Address");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 230, 60, 40);

        uptdCancel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uptdCancel1.setText("Cancel");
        uptdCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uptdCancel1ActionPerformed(evt);
            }
        });
        getContentPane().add(uptdCancel1);
        uptdCancel1.setBounds(320, 390, 103, 38);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
 
 
       try {
           Class.forName("com.mysql.jdbc.Driver"); //load the driver
           Connection con = DriverManager.getConnection("jdbc:mysql://192.168.0.20:3306/employeecrud", "Guian", "2ndyrGroupA"); //establishes the connection
           Statement stmt = (Statement) con.createStatement(); //get the connection stream(connection port)
           String query = "UPDATE   `employee` SET firstname='"+this.firstname.getText()+"',lastname='"+this.lastname.getText()+"',age='"+this.age.getText()+"',address='"+this.address.getText()+"',gender='"+this.gender.getText()+"'WHERE id='"+this.Id.getText()+"'";
           stmt.executeUpdate(query);
       
           con.close();
       } catch (Exception e) {
           System.out.println(e);
       }
JOptionPane.showMessageDialog(new JFrame(),"Employee Updated Successfully!");
    }//GEN-LAST:event_updateBtnActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void uptdCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uptdCancel1ActionPerformed
         landingPage home=new landingPage();
        home.show();
        dispose();
    }//GEN-LAST:event_uptdCancel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Id;
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JTextField firstname;
    private javax.swing.JTextField gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField lastname;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton uptdCancel1;
    // End of variables declaration//GEN-END:variables
}
